---
# tasks file for role

- name: install zabbix-web
  block:
    - name: import assert.yml
      ansible.builtin.import_tasks: assert.yml
      run_once: true
      delegate_to: localhost
    
    - name: install zabbix_web
      ansible.builtin.package:
        name: "{{ zabbix_frontend_packages }}"
        state: present
      notify:
        - restart httpd
    
    - name: configure zabbix_web
      ansible.builtin.template:
        src: zabbix.conf.php.j2
        dest: "{{ zabbix_configuration_path }}/zabbix.conf.php"
        mode: "0644"
      notify:
        - restart httpd
    
    - name: set selinux settings for zabbix_web
      ansible.posix.seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - httpd_can_network_connect
        - httpd_can_network_connect_db
        - httpd_can_connect_zabbix
      when:
        - ansible_selinux.status is defined
        - ansible_selinux.status == "enabled"
        - zabbix_frontend_configure == true
  when: zabbix_frontend_configure == true
  tags:
    - zabbix-frontend
    - zabbix-web
    - zabbix

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  when: zabbix_frontend_configure == true
